### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by baphomat** [Restes-au-bord/restes-au-bord#5]
Ce qu'on choisit d'afficher au client pour ses choix et le prix

**Comment by mrtryhard** [comment]
Donc, on a pas encore terminé le menu, beaucoup de travail à faire encore. 
[ ] Enregistrement ne semble pas fonctionner. Du moins, les items ne sont jamais remis correctement
[ ] Reset ne fonctionne pas encore (normal). On y pluggera un Patron de conception Command. 

On a ajouter le bouton pour ouvrir dans FenêtrePrincipale. 
Le formulaire est fait. 
On a ajouter une structure de Recette qui manquait. 
On a une liste de recette dans FenetrePrincipale (hardcoder, on changera ça plus tarD).

**Comment by wild006** [comment]
Le menu fonctionne désormais. 
Explications. 

- Annuler annule 1 changement à la fois 
- Reset annule tout les changements lorsque la fenêtre était ouverte.
- Enregistrer change le menu. 

La seule chose : 
L'interface ne "s'update" pas lorsqu'on clique sur Reset ou annuler (c'est normal, **pas urgent**, mais avec un refactor judicieux ça peux etre facile à faire).
