### ISSUE TITLE
concretement 

### ISSUE THREAD

**Issue by loulouX** [Restes-au-bord/restes-au-bord#9]
le code il marche on l'a arrangé
on a pas toujours pu initialiser le bouton reset et le bouton enregistrer
je pense ou bien je voudrais savoir si le menu prends de recette ou de stock???
je m'explique : dans menu il ne devrais pas y avoir des items qui n'ont pas été débloqué
chose qui n'est pas le cas
on s'est crée une classe aticleMenu qui est une arrayList qui va contenir la recette puis son prix 
on a aussi un peu modifier Menu

**Comment by wild006** [comment]
Commenter dans #5 plutôt. 
-- mrtryhard
